using System.Collections.Generic;

namespace SystemInfo_v2
{
    public class ClassesTurkishDescription
    {
        public Dictionary<string, string> Descriptions = new Dictionary<string, string>()
        {
            {"Win32_1394Controller", "1394 denetleyicisi hakkında bilgiler sağlar."},
            {"Win32_AssociatedProcessorMemory", "İşlemci ve bellek arasındaki ilişki hakkında bilgiler sağlar."},
            {"Win32_Product", "Yazılım Ürünleri hakkında genel bilgi sağlar." },
            {"Win32_AutochkSetting", "Autochk ayarları hakkında bilgiler sağlar."},
            {"Win32_BaseBoard", "Ana kart hakkında bilgiler sağlar."},
            {"Win32_Battery", "Pil hakkında bilgiler sağlar."},
            {"Win32_BIOS", "Sistem BIOS'u hakkında bilgiler sağlar."},
            {"Win32_BootConfiguration", "Önyükleme yapılandırması hakkında bilgiler sağlar."},
            {"Win32_Bus", "Sistemdeki otobüsleri (bus) hakkında bilgiler sağlar."},
            {"Win32_CacheMemory", "Önbellek belleği hakkında bilgiler sağlar."},
            {"Win32_CDROMDrive", "CD-ROM sürücüsü hakkında bilgiler sağlar."},
            {"Win32_CIMLogicalDeviceCIMDataFile", "CIM veri dosyaları hakkında bilgiler sağlar."},
            {"Win32_ComputerSystem", "Bilgisayar sistemi hakkında genel bilgiler sağlar."},
            {"Win32_ComputerSystemProcessor", "Bilgisayar sistemi ve işlemci hakkında bilgiler sağlar."},
            {"Win32_CurrentProbe", "Akım probu hakkında bilgiler sağlar."},
            {"Win32_DesktopMonitor", "Masaüstü monitörü hakkında bilgiler sağlar."},
            {"Win32_DeviceBus", "Cihaz otobüsü hakkında bilgiler sağlar."},
            {"Win32_DeviceChangeEvent", "Cihaz değişiklikleri hakkında bilgiler sağlar."},
            {"Win32_DeviceMemoryAddress", "Cihaz bellek adresi hakkında bilgiler sağlar."},
            {"Win32_DeviceSettings", "Cihaz ayarları hakkında bilgiler sağlar."},
            {"Win32_DiskDrive", "Disk sürücüsü hakkında bilgiler sağlar."},
            {"Win32_DiskDriveToDiskPartition", "Disk sürücüsü ile disk bölümü arasındaki ilişki hakkında bilgiler sağlar."},
            {"Win32_DiskPartition", "Disk bölümü hakkında bilgiler sağlar."},
            {"Win32_DisplayConfiguration", "Ekran ayarları hakkında bilgiler sağlar."},
            {"Win32_DisplayControllerConfiguration", "Ekran kontrolcüsü yapılandırması hakkında bilgiler sağlar."},
            {"Win32_DMAChannel", "DMA kanalı hakkında bilgiler sağlar."},
            {"Win32_DriverForDevice", "Cihaz sürücüsü hakkında bilgiler sağlar."},
            {"Win32_Fan", "Fan hakkında bilgiler sağlar."},
            {"Win32_FloppyController", "Disket sürücü kontrolcüsü hakkında bilgiler sağlar."},
            {"Win32_FloppyDrive", "Disket sürücü hakkında bilgiler sağlar."},
            {"Win32_IDEController", "IDE kontrolcüsü hakkında bilgiler sağlar."},
            {"Win32_IDEControllerDevice", "IDE kontrolcüsü cihazları hakkında bilgiler sağlar."},
            {"Win32_InfraredDevice", "Kızılötesi aygıt hakkında bilgiler sağlar."},
            {"Win32_IRQResource", "IRQ kaynaklarının özelliklerini sağlar."},
            {"Win32_Keyboard", "Klavye aygıtı hakkında bilgiler sağlar."},
            {"Win32_LogicalDisk", "Mantıksal diskler hakkında bilgiler sağlar."},
            {"Win32_LogicalDiskRootDirectory", "Mantıksal disklerin ana dizinlerinin özelliklerini sağlar."},
            {"Win32_LogicalDiskToPartition", "Mantıksal disklere atanan bölümler hakkında bilgiler sağlar."},
            {"Win32_LogicalProgramGroup", "Bir program grubunun özelliklerini sağlar."},
            {"Win32_LogicalProgramGroupDirectory", "Bir program grubunun ana dizin özelliklerini sağlar."},
            {"Win32_LogicalProgramGroupItem", "Bir program grubuna dahil olan öğelerin özelliklerini sağlar."},
            {"Win32_LogicalProgramGroupItemDataFile", "Bir program grubuna dahil olan öğelerin veri dosyaları hakkında bilgiler sağlar."},
            {"Win32_MappedLogicalDisk", "Bir ağ paylaşımına haritalanan mantıksal disk hakkında bilgiler sağlar."},
            {"Win32_MemoryArray", "Bellek dizisi hakkında bilgiler sağlar."},
            {"Win32_MemoryArrayLocation", "Bellek dizisinin bulunduğu konum hakkında bilgiler sağlar."},
            {"Win32_MemoryDevice", "Bellek aygıtı hakkında bilgiler sağlar."},
            {"Win32_MemoryDeviceArray", "Bellek aygıtı dizisi hakkında bilgiler sağlar."},
            {"Win32_MemoryDeviceLocation", "Bellek aygıtının bulunduğu konum hakkında bilgiler sağlar."},
            {"Win32_MotherboardDevice", "Anakart aygıtları hakkında bilgiler sağlar."},
            {"Win32_NetworkAdapter", "Ağ adaptörü hakkında bilgiler sağlar."},
            {"Win32_NetworkAdapterConfiguration", "Ağ adaptörü yapılandırması hakkında bilgiler sağlar."},
            {"Win32_NetworkAdapterSetting", "Ağ adaptörü ayarları hakkında bilgiler sağlar."},
            {"Win32_NetworkClient", "Ağ istemcisi hakkında bilgiler sağlar."},
            {"Win32_NetworkConnection", "Ağ bağlantısı hakkında bilgiler sağlar."},
            {"Win32_NetworkLoginProfile", "Ağ oturumu hakkında bilgiler sağlar."},
            {"Win32_NetworkProtocol", "Ağ protokolleri hakkında bilgiler sağlar."},
            {"Win32_OnBoardDevice", "Entegre donanım aygıtları hakkında bilgiler sağlar."},
            {"Win32_ParallelPort", "Paralel port hakkında bilgiler sağlar."},
            {"Win32_PCMCIAController", "PCMCIA kontrolcüsü hakkında bilgiler sağlar."},
            {"Win32_PhysicalMemory", "Fiziksel bellek modülleri hakkında bilgiler sağlar."},
            {"Win32_PhysicalMemoryArray", "Fiziksel bellek dizisi hakkında bilgiler sağlar."},
            {"Win32_PhysicalMemoryLocation", "Fiziksel bellek konumu hakkında bilgiler sağlar."},
            {"Win32_PnPAllocatedResource", "PNP atanan kaynak hakkında bilgiler sağlar."},
            {"Win32_PnPDevice", "PNP aygıtları hakkında bilgiler sağlar."},
            {"Win32_PnPDeviceProperty", "PNP aygıt özellikleri hakkında bilgiler sağlar."},
            {"Win32_PnPEntity", "PNP varlıkları hakkında bilgiler sağlar."},
            {"Win32_PointingDevice", "İşaret cihazları (mouse, touchpad, vb.) hakkında bilgiler sağlar."},
            {"Win32_PortableBattery", "Taşınabilir pil hakkında bilgiler sağlar."},
            {"Win32_PortConnector", "Port konektörü hakkında bilgiler sağlar."},
            {"Win32_PortResource", "Port kaynakları hakkında bilgiler sağlar."},
            {"Win32_POTSModem", "Modem hakkında bilgiler sağlar."},
            {"Win32_POTSModemToSerialPort", "Modem seri bağlantısı hakkında bilgiler sağlar."},
            {"Win32_Printer", "Yazıcı hakkında bilgiler sağlar."},
            {"Win32_PrinterConfiguration", "Yazıcı yapılandırması hakkında bilgiler sağlar." },
            {"Win32_PrinterController", "Yazıcı kontrolcüsü hakkında bilgiler sağlar."},
            {"Win32_PrinterDriver", "Yazıcı sürücüsü hakkında bilgiler sağlar."},
            {"Win32_PrinterDriverDll", "Yazıcı sürücü DLL'si hakkında bilgiler sağlar."},
            {"Win32_PrinterSetting", "Yazıcı ayarları hakkında bilgiler sağlar."},
            {"Win32_PrinterShare", "Paylaşılan yazıcılar hakkında bilgiler sağlar."},
            {"Win32_PrintJob", "Yazdırma işlemi hakkında bilgiler sağlar."},
            {"Win32_Processor", "İşlemci hakkında bilgiler sağlar."},
            {"Win32_SCSIController", "SCSI kontrolcüsü hakkında bilgiler sağlar."},
            {"Win32_SCSIControllerDevice", "SCSI cihazları hakkında bilgiler sağlar."},
            {"Win32_SerialPort", "Seri port hakkında bilgiler sağlar."},
            {"Win32_SerialPortConfiguration", "Seri port yapılandırması hakkında bilgiler sağlar."},
            {"Win32_SerialPortSetting", "Seri port ayarları hakkında bilgiler sağlar" },
            {"Win32_SMBIOSMemory", "SMBIOS tarafından belirtilen bellek aygıtları hakkında bilgiler sağlar."},
            {"Win32_SoundDevice", "Ses aygıtı hakkında bilgiler sağlar."},
            {"Win32_TapeDrive", "Manyetik bant sürücüsü hakkında bilgiler sağlar."},
            {"Win32_TCPIPPrinterPort", "TCP/IP yazıcı bağlantı noktası hakkında bilgiler sağlar."},
            {"Win32_USBController", "USB denetleyicisi hakkında bilgiler sağlar."},
            {"Win32_USBControllerDevice", "Bir USB denetleyicisi ile ilişkili bir aygıt hakkında bilgiler sağlar."},
            {"Win32_VideoController", "Video denetleyicisi hakkında bilgiler sağlar."},
            {"Win32_VideoSettings", "Video ayarları hakkında bilgiler sağlar."},
            {"Win32_VoltageProbe", "Gerilim ölçer cihaz hakkında bilgiler sağlar."}

        };
    }
}
